### ISSUE TITLE
More granular push notification options

### ISSUE THREAD

**Issue by themightychris** [SquadQuest/SquadQuest#161]
Add options to settings to let people select what they get push notifications for

## Options

- Friend requests
- Event invitations
- Updates to events I'm RSVPd to
- Friend-only events posted to my topics
- Public events posted to my topics

## TODO

- [x] add section to settings screen
- [x] save to an enum array in the profile
- [ ] check options in various backend functions before sending push notification
